apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-config
  namespace: elastic
  labels:
    app: elasticsearch
data:
  elasticsearch.yml: |-
    cluster.name: elasticsearch-cluster
    network.host: 0.0.0.0
    discovery.zen.minimum_master_nodes: 1
    discovery.type: single-node
  ES_JAVA_OPTS: -Xms512m -Xmx512m