apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: web-ingress-tls
spec:
  tls:
    - hosts:
      - hello-world.info
      secretName: tls-secret
  rules:
    - host: hello-world.info
      http:
        paths:
        - path: /
          backend:
            serviceName: web
            servicePort: 8080