apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: db
spec:
  replicas: {{ .Values.db.replicaCount }}
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - image: "{{ .Values.db.image.repository }}:{{ .Values.db.image.tag }}"
        name: db
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: db-data
      volumes:
      - name: db-data
        emptyDir: {} 
