apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  type: {{ .Values.db.service.type }}
  ports:
  - port: {{ .Values.db.service.port }}
    targetPort: {{ .Values.db.service.port }}
  selector:
    app: db