apiVersion: v1
kind: Service
metadata:
  name: logstash
  namespace: elastic
  labels:
    app: logstash
spec:
  selector:
    app: logstash
  ports:
    - name: beats
      port: 5555
      protocol: TCP
      targetPort: beats
    - name: monitor
      port: 9600
      protocol: TCP
      targetPort: monitor