---
apiVersion: v1
kind: ConfigMap
metadata:
  name: metricbeat-deployment-config
  namespace: elastic
  labels:
    app: metricbeat
data:
  metricbeat.yml: |-
    metricbeat.config.modules:
      # Mounted `metricbeat-daemonset-modules` configmap:
      path: ${path.config}/modules.d/*.yml
      # Reload module configs as they change:
      reload.enabled: false

    output.elasticsearch:
      hosts: ['elasticsearch-0.elasticsearch.elastic:9200']

    setup:
      kibana:
        host: "http://kibana:5601"
      dashboards:
        enabled: true
        index: "metricbeat-*"
        retry:
          enabled: true
          interval: 30
      template:
        enabled: true

    xpack.monitoring:
      enabled: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: metricbeat-deployment-modules
  namespace: elastic
  labels:
    app: metricbeat
data:
  # This module requires `kube-state-metrics` up and running under `kube-system` namespace
  kubernetes.yml: |-
    - module: kubernetes
      metricsets:
        - state_node
        - state_deployment
        - state_replicaset
        - state_pod
        - state_container
        - event
      period: 10s
      host: ${NODE_NAME}
      hosts: ["kube-state-metrics.kube-system.svc.cluster.local:8080"]
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: metricbeat-daemonset-config
  namespace: elastic
  labels:
    app: metricbeat
data:
  metricbeat.yml: |-
    metricbeat.config.modules:
      # Mounted `metricbeat-daemonset-modules` configmap:
      path: ${path.config}/modules.d/*.yml
      # Reload module configs as they change:
      reload.enabled: false

    # To enable hints based autodiscover uncomment this:
    metricbeat.autodiscover:
     providers:
       - type: kubernetes
         host: ${NODE_NAME}
         hints.enabled: true

    processors:
      - add_host_metadata:
          netinfo.enabled: false

    output.elasticsearch:
      hosts: ['elasticsearch-0.elasticsearch.elastic:9200']

    setup.kibana:
      host: "http://kibana:5601"

    xpack.monitoring:
      enabled: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: metricbeat-daemonset-modules
  namespace: elastic
  labels:
    app: metricbeat
data:
  system.yml: |-
    - module: system
      period: 10s
      metricsets:
        - cpu             # CPU usage
        - load            # CPU load averages
        - memory          # Memory usage
        - network         # Network IO
        - process         # Per process metrics
        - process_summary # Process summary
        - uptime          # System Uptime
        - socket_summary  # Socket summary
        - core           # Per CPU core usage
        - diskio         # Disk IO
        - filesystem     # File system usage for each mountpoint
        - fsstat         # File system summary metrics
        - raid           # Raid
        - socket         # Sockets and connection info (linux only)
      processes: ['.*']
      process.include_top_n:
        by_cpu: 5      # include top 5 processes by CPU
        by_memory: 5   # include top 5 processes by memory
      cpu.metrics:  ["percentages"]  # The other available options are normalized_percentages and ticks.
      core.metrics: ["percentages"]  # The other available option is ticks.

    - module: system
      period: 1m
      metricsets:
        - filesystem
        - fsstat
      processors:
      - drop_event.when.regexp:
          system.filesystem.mount_point: '^/(sys|cgroup|proc|dev|etc|host|lib)($|/)'
  kubernetes.yml: |-
    - module: kubernetes
      metricsets:
        - node
        - system
        - pod
        - container
        - volume
      period: 10s
      host: ${NODE_NAME}
      hosts: ["localhost:10255"]
  docker.yml: |-
    - module: docker
      metricsets:
        - "container"
        - "cpu"
        - "diskio"
        - "event"
        - "healthcheck"
        - "info"
        - "image"
        - "memory"
        - "network"
      hosts: ["unix:///var/run/docker.sock"]
      period: 10s
      enabled: true
  elastic.yml: |-
    - module: elasticsearch
      metricsets:
        - node
        - node_stats
        - cluster_stats
        - index
        - index_recovery
        - index_summary
        - shard
      period: 10s
      hosts: ["elasticsearch-0.elasticsearch.elastic:9200"]
    - module: logstash
      metricsets: ["node", "node_stats"]
      enabled: true
      period: 10s
      hosts: ["logstash:9600"]
    - module: kibana
      metricsets: ["status"]
      period: 10s
      hosts: ["kibana:5601"]
      basepath: ""
      enabled: true