apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: heartbeat
  labels:
    app: heartbeat
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: heartbeat
subjects:
  - kind: ServiceAccount
    name: heartbeat
    namespace: elastic