---
apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
  namespace: elastic
  labels:
    app: logstash-config
data:
  logstash.yml: |-
    http.host: "0.0.0.0"
    config.reload.automatic: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config-pipeline
  namespace: elastic
  labels:
    app: logstash
data:
  input_main: |-
    input {
      beats {
          port => 5555
      }
    }
  output_main: |-
    output {
        elasticsearch {
          hosts => ["elasticsearch-0.elasticsearch.elastic:9200"]
          index => "%{[@metadata][beat]}-%{[@metadata][version]}-%{+YYYY.MM.dd}"
        }
    }